# Generated by Django 4.2.3 on 2023-07-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='name',
        ),
    ]
