# Generated by Django 4.2.3 on 2023-07-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
